server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        default-requeue-rejected: false
#        retry:
#          enabled: true
#          max-attempts: 3
#          initial-interval: 5s
#          multiplier: 2

